Repository TheSwiftists/effective-swift, pull requests merged in 2020-12, with the labels that each got.

#37 item16. public 클래스에서는 public 필드가 아닌 접근자 메서드를 사용하라
  chapter4/item16.md
Labels: contents

#38 item20. 추상 클래스보다는 인터페이스를 우선하라
  4장_클래스와_인터페이스/item20.md
Labels: contents

#52 아이템별 담당자 및 파일 링크 추가(11월 14일) + 잘못 들어간 파일 이동
  4장_클래스와_인터페이스/item16.md
  README.md
Labels: docs

#36 Item21. 인터페이스는 구현하는 쪽을 생각해 설계하라
  chapter4/item21.md
Labels: WIP, contents, modify

#48 item15. 클래스와 멤버의 접근 권한을 최소화 하라.
  chapter4/item15.md
Labels: contents

#59 아이템별 담당자 및 파일 링크 추가(12월 5일 모임) + 리드미 목차 테이블에 서브 타이틀 열(Column) 추가
  README.md
Labels: docs

#69 합니다체로 변경합니다
  2장_객체_생성과_파괴/item2.md
  2장_객체_생성과_파괴/item3.md
  3장_모든_객체의_공통_메서드/item10.md
  3장_모든_객체의_공통_메서드/item13.md
Labels: contents, modify
