Repository TheSwiftists/effective-swift, pull requests merged in 2020-11, with the labels that each got.

#16 아이템별 담당자 및 파일 링크 추가 - 2번째 모임
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  chapter1/item0.md
  chapter10/item0.md
  chapter11/item0.md
  chapter12/item0.md
  chapter4/item0.md
  chapter5/item0.md
  chapter6/item0.md
  chapter7/item0.md
  chapter8/item0.md
  chapter9/item0.md
Labels: documentation

#14 Item10. equals는 일반 규약을 지켜 재정의하라
  README.md
  chapter3/item10.md
Labels: contents

#13 Item 6. 불필요한 객체 생성을 피하라
  README.md
  chapter2/item6.md
Labels: contents

#22 item12. toString을 항상 재정의하라
  README.md
  chapter3/item12.md
Labels: contents

#23 잘못된 챕터 링크 수정
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#10 Item14. Comparable을 구현할지 고려하라
  README.md
  chapter3/item0.md
  chapter3/item14.md
Labels: contents

#12 Item7. 다 쓴 객체 참조를 해제하라
  README.md
  chapter2/item7.md
Labels: contents

#30 -니다 체로 변경
  chapter2/item1.md
  chapter2/item6.md
Labels: modify

#11 Item11. equals를 재정의하려거든 hashCode도 재정의하라
  README.md
  chapter3/Item11.md
Labels: contents

#21 item9. try-finally보다는 try-with-resources를 사용해라
  README.md
  chapter2/item9.md
Labels: contents

#31 Item1 에서 정적 팩터리 메서드를 사용하면 좋은 예시에 대해 추가했습니다.
  chapter2/item1.md
Labels: update

#15 Item13. clone 재정의는 주의해서 진행하라
  README.md
  chapter3/item13.md
Labels: contents

#34 item4 문체 수정
  chapter2/item4.md
Labels: modify

#33 Item8. finalizer와 cleaner 사용을 피하라
  chapter2/item8.md
Labels: contents

#42 폴더에 이름 붙임
  10장_예외/item0.md
  11장_동시성/item0.md
  12장_직렬화/item0.md
  2장_객체_생성과_파괴/item1.md
  2장_객체_생성과_파괴/item2.md
  2장_객체_생성과_파괴/item3.md
  2장_객체_생성과_파괴/item4.md
  2장_객체_생성과_파괴/item5.md
  2장_객체_생성과_파괴/item6.md
  2장_객체_생성과_파괴/item7.md
  2장_객체_생성과_파괴/item8.md
  2장_객체_생성과_파괴/item9.md
  2장_객체_생성과_파괴/resources/item3-singleton.png
  3장_모든_객체의_공통_메서드/item10.md
  3장_모든_객체의_공통_메서드/item11.md
  3장_모든_객체의_공통_메서드/item12.md
  3장_모든_객체의_공통_메서드/item13.md
  3장_모든_객체의_공통_메서드/item14.md
  5장_제네릭/item0.md
  6장_열거_타입과_애너테이션/item0.md
  7장_람다와_스트림/item0.md
  8장_메서드/item0.md
  9장_일반적인_프로그래밍_원칙/item0.md
  README.md
  chapter8/item0.md
  chapter9/item0.md
Labels: docs

#32 Item5. 의존성 주입 iOS 활용 예시 수정 및 문체 통일
  2장_객체_생성과_파괴/item5.md
Labels: contents, modify

#41 Item 17. 변경 가능성을 최소화하라
  4장_클래스와_인터페이스/item17.md
Labels: contents
