Repository TheSwiftists/effective-swift, pull requests merged in 2021-06, with the labels that each got.

#76 Item39. 명명패턴보단 애너테이션을 사용하라
  6장_열거_타입과_애너테이션/item39.md
  README.md
Labels: Heidi, contents

#86 item49. 매개변수가 유효한지 검사하라
  8장_메서드/item49.md
  README.md
Labels: Gwonii, Heidi, contents

#97 item56. 공개된 API 요소에는 항상 문서화 주석을 작성하라
  8장_메서드/item56.md
  README.md
Labels: Gwonii, Heidi, Lin, contents

#118 Item64. 객체는 인터페이스를 사용해 참조하라
  9장_일반적인_프로그래밍_원칙/item0.md
  9장_일반적인_프로그래밍_원칙/item64.md
  README.md
Labels: Gwonii, Heidi, Lin, contents

#119 Item63. 문자열 연결은 느리니 주의하라
  9장_일반적인_프로그래밍_원칙/item63.md
  README.md
Labels: Gwonii, Lin, contents

#101 Item 59. 라이브러리를 익히고 사용하라
  9장_일반적인_프로그래밍_원칙/item59.md
  README.md
Labels: Gwonii, Heidi, Lin, contents

#117 Item 68. 일반적으로 통용되는 명명 규칙을 따르라
  9장_일반적인_프로그래밍_원칙/item68.md
Labels: Gwonii, Heidi, Lin, contents

#100 item 57. 지역변수의 범위를 최소화하라
  5장_제네릭/item27.md
  9장_일반적인_프로그래밍_원칙/item57.md
  README.md
Labels: Gwonii, Heidi, Lin, contents

#123 Item82. 스레드 안정성 수준 문서화
  11장_동시성/item82.md
  README.md
Labels: Gwonii, Heidi, Lin, contents

#126 Item77. 예외를 무시하지 말라
  10장_예외/item77.md
  README.md
Labels: Gwonii, Heidi, Lin, contents
