Repository TheSwiftists/effective-swift, pull requests merged in 2021-01, with the labels that each got.

#51 item22. 인터페이스는 타입을 정의하는 용도로만 사용하라
  4장_클래스와_인터페이스/item22.md
Labels: contents

#46 Item 25. 톱레벨 클래스는 한 파일에 하나만 담으라
  chapter4/item25.md
Labels: contents

#55 Item 23. 태그 달린 클래스보다는 클래스 계층구조를 활용하라
  4장_클래스와_인터페이스/item23.md
  4장_클래스와_인터페이스/resources/buttons.png
Labels: contents

#57 item28. 배열보다는 리스트를 사용하라
  5장_제네릭/item28.md
Labels: contents

#60 item24. 멤버 클래스는 되도록 static으로 만들라
  4장_클래스와_인터페이스/item24.md
Labels: Jason, contents

#61 item 32. 제네릭과 가변인수(varargs)를 함께 쓸 때는 신중하라
  5장_제네릭/item32.md
Labels: Heidi, contents

#81 아이템 목록 업데이트
  4장_클래스와_인터페이스/item15.md
  4장_클래스와_인터페이스/item21.md
  4장_클래스와_인터페이스/item25.md
  README.md
Labels: docs

#53 Item 18. 상속보다는 컴포지션을 사용하라
  4장_클래스와_인터페이스/item18.md
Labels: contents

#54 item19. 상속을 고려해 설계하고 문서화하라. 그러지 않았다면 상속을 금지하라
  4장_클래스와_인터페이스/item19.md
Labels: contents

#62 Item30. 이왕이면 제네릭 메서드로 만들라
  5장_제네릭/item30.md
Labels: contents

#71 item40. @Override 애너테이션을 일관되게 사용하라
  6장_열거_타입과_애너테이션/item40.md
  README.md
Labels: contents
