Repository TheSwiftists/effective-swift, pull requests merged in 2021-05, with the labels that each got.

#92 Item46. 부작용없는 함수를 만들어라
  7장_람다와_스트림/item46.md
  README.md
Labels: Gwonii, Heidi, contents

#91 Item51. 메서드 시그니처를 신중히 설계하라
  8장_메서드/item51.md
  README.md
Labels: Gwonii, Heidi, contents

#94 Item55. 옵셔널 반환 신중히 하라.
  8장_메서드/item55.md
  README.md
Labels: Gwonii, Heidi, Lin, contents

#134 Item70. 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라
  10장_예외/item70.md
  README.md
Labels: Gwonii, Heidi, Lin, contents

#128 Item73. 추상화 수준에 맞는 예외를 던져라
  10장_예외/item73.md
  README.md
Labels: Gwonii, Heidi, Lin, contents

#74 item34. int 상수 대신 열거 타입을 사용하라
  6장_열거_타입과_애너테이션/item34.md
Labels: contents

#75 item37. ordinal 인덱싱 대신 EnumMap을 사용하라
  6장_열거_타입과_애너테이션/item37.md
Labels: Heidi, contents

#90 item53. 가변인수는 신중히 사용하라
  8장_메서드/item53.md
  README.md
Labels: Gwonii, Heidi, contents

#113 Item60. 정확한 답이 필요하다면 float과 double은 피하라
  9장_일반적인_프로그래밍_원칙/item60.md
  README.md
Labels: Gwonii, Heidi, Lin, contents

#85 Item43. 람다보다는 메서드 참조를 사용하라
  7장_람다와_스트림/item43.md
  README.md
Labels: Gwonii, Heidi, Lin, contents
